name: Unit Tests

on: [push]

jobs:
  test:
    name: Tests - React Native Testing Library
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@master
      - uses: c-hive/gha-yarn-cache@v1

      - name: Install node modules
        run: |
          yarn install
      - name: Run test
        run: |
          yarn test
